class C_SceneEntity : public C_PointEntity
{
	// MNotSaved
	bool m_bIsPlayingBack;
	// MNotSaved
	bool m_bPaused;
	// MNotSaved
	bool m_bMultiplayer;
	// MNotSaved
	bool m_bAutogenerated;
	// MNotSaved
	bool m_bAllRequirementsComplete;
	// MNotSaved
	float32 m_flForceClientTime;
	// MNotSaved
	uint16 m_nSceneStringIndex;
	// MNotSaved
	bool m_bClientOnly;
	// MNotSaved
	CHandle< C_BaseModelEntity > m_hOwner;
	// MNotSaved
	C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > > m_hActorList;
	// MNotSaved
	bool m_bWasPlaying;
	// MNotSaved
	CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents;
	// MNotSaved
	float32 m_flCurrentTime;
};
